name: client
description: A new Flutter project.

publish_to: 'none' 
version: 0.0.1+73

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  simple_autocomplete_formfield: ^0.3.0
  firebase_core: ^1.6.0
  firebase_analytics: ^8.3.2
  firebase_auth: ^3.1.1
  modal_progress_hud: ^0.1.3
  provider: ^6.0.1
  cloud_firestore: ^2.5.3
  excel: ^1.1.5
  shared_preferences: ^2.0.7





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icons/
    - images/
